using System;

namespace Microsoft.FeatureFlighting.Common.Model
{
    /// <summary>
    /// Feature usage report
    /// </summary>
    public class FeatureUsageReportDto
    {
        /// <summary>
        /// Report startement
        /// </summary>
        public string UsageStatement { get; set; }

        /// <summary>
        /// Days the flight has been active
        /// </summary>
        public int ActivePeriod { get; set; }

        /// <summary>
        /// Days the flight has been inactive
        /// </summary>
        public int InactivePeriod { get; set; }

        /// <summary>
        /// Days the flight hasn't been evaluated
        /// </summary>
        public int UnusedPeriod { get; set; }

        /// <summary>
        /// Indicates if the feature has been active for too long
        /// </summary>
        public bool HasActivationPeriodExceeded { get; set; }
        
        /// <summary>
        /// Indicates if the feature flight has been disabled for too long
        /// </summary>
        public bool HasDisabledPeriodExceeded { get; set; }
        
        /// <summary>
        /// Indicates if the feature remains unused for too long
        /// </summary>
        public bool HasUnsedPeriodExceeded { get; set; }

        /// <summary>
        /// Indicates of the feature iis newly added
        /// </summary>
        public bool IsNew { get; set; }

        /// <summary>
        /// Indicates if alert should be shown
        /// </summary>
        public bool ShowAlert { get; set; }

        /// <summary>
        /// Indicates if alerts are sent for the feature flight
        /// </summary>
        public bool EnableAlerts { get; set; }

        /// <summary>
        /// Report generated by
        /// </summary>
        public string GeneratedBy { get; set; }

        /// <summary>
        /// When the report was generated
        /// </summary>
        public DateTime GeneratedOn { get; set; }
    }
}
