<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.86.1" />
    <PackageReference Include="Microsoft.Identity.ServiceEssentials.AspNetCore" Version="2.5.3" />
    <PackageReference Include="Microsoft.Identity.ServiceEssentials.Caching" Version="2.5.3" />
    <PackageReference Include="Microsoft.IdentityModel.Validators" Version="8.21.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.3.2" />
    <PackageReference Include="MSTest.TestFramework" Version="4.3.2" />
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\API\Microsoft.FeatureFlighting.API.csproj" />
  </ItemGroup>

</Project>
